#ifndef GENERAL_CONFIG_H
#define GENERAL_CONFIG_H

// #define DEFAULT_BUFFER_SIZE 4096
// #define DEFAULT_BUFFER_SIZE 50000

#define VOLUME_STEP 0.05f


#define IO_EXPANDER

// LCD configuration
#define LCD_RUN_THREADED

// fft beat detection teleplot telemetry
// #define BEAT_TELEMETRY


#define PRIORITY_AUDIO_TASK 6
#define PRIORITY_LCD_TASK 7
#define PRIORITY_ADC_BUTTON 6
#define PRIORITY_BATTERY_MONITOR 6

#define ADC_BATTERY_CONVERSION 2
#define BATTERYHIGH 0
#define BATTERYLOW 1
#define BATTERYVERYLOW 2
#define BATTERYVERYLOWVOLTAGE 3200
#define BATTERYLOWVOLTAGE 3400

#endif  // GENERAL_CONFIG_H
